let input = document.getElementById("input");

let output = document.getElementById("output");
input.onkeyup = (e) => {
    output.innerText = `module program(output reg [8:7] program);initial program = 72'h${parseInt(assemble(input.value), 2).toString(16)};endmodule // generated by chamoisIDE github.com/chamoisthefirst/chamoisIDE`;
}